version: '1'

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./
      dockerfile: ./php-fpm/Dockerfile
    restart: always
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
    networks:
      - drupal-network
    depends_on:
      - db
    
  nginx:
    container_name: nginx
    image: nginx:1.19-alpine
    restart: always
    ports:
      - "3001:80"
      - "3000:8080"
    volumes:
      - ./src:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    networks:
      - drupal-network

  db:
    container_name: db
    build:
      context: ./
      dockerfile: ./php-fpm/Dockerfile
    restart: always
    environment:
      MYSQL_USER: 'drupal'
      MYSQL_PASSWORD: 'drupal'
      MYSQL_DATABASE: 'drupal'
      MYSQL_ROOT_PASSWORD: 'drupal'
    volumes:
      - ./sql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - drupal-network

networks:
  drupal-network:
    driver: bridge