version: '1'

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./
      dockerfile: ./php-fpm/Dockerfile
    restart: always
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
    networks:
      - drupal-network
    depends_on:
      - db

  # php-myadmin:
  #   container_name: phpmyadmin
  #   image: phpmyadmin
  #   restart: always
  #   ports:
  #     - "8080:80"
  #   environment:
  #     PMA_HOST: db
  #     PMA_PORT: 3306
  #     PMA_USER: 'root'
  #     PMA_PASSWORD: 'root'
  #   networks:
  #     - drupal-network
  #   depends_on:
  #     - db
    
  nginx:
    container_name: nginx
    image: nginx:1.19-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - php-fpm
    networks:
      - drupal-network

  db:
    container_name: db
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: 'drupal'
      MYSQL_PASSWORD: 'drupal'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'drupal'
    volumes:
      - ./sql-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - drupal-network

networks:
  drupal-network:
    driver: bridge